version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
      - sse-server
    ports:
      - 7800:7800

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile.prod
    image: qa-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  qa-ui:
    build:
      context: qa-ui
      dockerfile: Dockerfile.prod
    image: qa-ui-prod
    restart: "on-failure"
    expose:
      - 3000
    depends_on:
      - qa-api
      - sse-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"
        
  llm-api:
    build: llm-api
    image: llm-api
    restart: "no"
    expose:
      - 7000

  database:
    container_name: database-server-dab-p2-139c502d-17da-49bb-bcaa-7c683af92b3c
    image: postgres:14.1
    restart: "unless-stopped"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
  
  sse-server:
    build:
      context: sse-server
      dockerfile: Dockerfile.prod
    image: sse-server-prod
    restart: "on-failure"
    expose:
      - 5050
    env_file:
      - project.env
    depends_on:
      - redis
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379