version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
      - sse-server
    ports:
      - 7800:7800

  programming-api:
    build:
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  programming-ui:
    build:
      context: programming-ui
      dockerfile: Dockerfile.prod
    image: programming-ui-prod
    restart: "on-failure"
    expose:
      - 3000
    depends_on:
      - programming-api
      - sse-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  sse-server:
    build:
      context: sse-server
      dockerfile: Dockerfile.prod
    image: sse-server-prod
    restart: "on-failure"
    expose:
      - 5050
    env_file:
      - project.env
    depends_on:
      - redis
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  grader-api:
    build:
      context: grader-api
      dockerfile: Dockerfile.prod
    image: grader-api-prod
    restart: "on-failure"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  database:
    container_name: database-server-dab-p1-139c502d-17da-49bb-bcaa-7c683af92b3c
    image: postgres:14.1
    restart: "unless-stopped"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379