apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sse-server-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sse-server-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
